### ISSUE TITLE
[Python] pyarrow needs to depend on numpy>=1.10 (not 1.9)

### ISSUE THREAD

**Issue by toddfarmer** [toddfarmer/arrow-migration#1112]
***Note**: This issue was originally created as [ARROW-1124](https://issues.apache.org/jira/browse/ARROW-1124). Please see the [migration documentation](https://gist.github.com/toddfarmer/12aa88361532d21902818a6044fda4c3) for further details.*

### Original Issue Description:
The pyarrow package lists numpy >= 1.9 as a dependency in setup.py - however, it causes an exception at import time with numpy 1.9.

Repro steps:

{{$ pip install numpy==1.9
...
$ pip install pyarrow
...
$ python -c 'import pyarrow'
RuntimeError: module compiled against API version a but this version of numpy is 9
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/dima/envs/pyarrow-bug/lib/python2.7/site-packages/pyarrow/__init__.py", line 28, in <module>
    from pyarrow.lib import cpu_count, set_cpu_count
  File "pyarrow/lib.pyx", line 40, in init pyarrow.lib (/arrow/python/build/temp.linux-x86_64-2.7/lib.cxx:62119)
ImportError: numpy.core.multiarray failed to import
}}

(Additionally, requirements.txt lists "numpy>=1.7" - though it doesn't look like it's used at all.)

**Comment by toddfarmer** [comment]
***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-1124?focusedCommentId=16052748) by Uwe Korn (uwe):*
I made a PR to update the dependency specification to `>=1.10`: https://github.com/apache/arrow/pull/758

Actually for Python 2, we could build the wheel with NumPy 1.9 to support `>=1.9` as a python 2 specification. `[~dimaryaz]` if there is a need for you to have 1.9 support for Python 2, feel free to make a PR that adds this dependency conditionally only for Python 2 and adjust the manylinux1 build script.

**Comment by toddfarmer** [comment]
***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-1124?focusedCommentId=16052912) by Dima Ryazanov (dimaryaz):*
Oh, I don't actually need NumPy 1.9 support - but it's breaking Travis CI because the Python 2 environment comes with NumPy 1.9 pre-installed. Simply requiring 1.10 would fix that.

**Comment by toddfarmer** [comment]
***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-1124?focusedCommentId=16052919) by Uwe Korn (uwe):*
Issue resolved by pull request 758
<https://github.com/apache/arrow/pull/758>
