### ISSUE TITLE
[Python] whl is not a supported wheel on this platform on Debian/Jessie

### ISSUE THREAD

**Issue by toddfarmer** [toddfarmer/arrow-migration#1335]
***Note**: This issue was originally created as [ARROW-1378](https://issues.apache.org/jira/browse/ARROW-1378). Please see the [migration documentation](https://gist.github.com/toddfarmer/12aa88361532d21902818a6044fda4c3) for further details.*

### Original Issue Description:
pip does not find 0.6.0:

```java
# pip install --verbose pyarrow==0.6.0
Downloading/unpacking pyarrow==0.6.0
  Could not fetch URL https://pypi.python.org/simple/pyarrow/0.6.0: 404 Client Error: Not Found (pyarrow/0.6.0)
  Will skip URL https://pypi.python.org/simple/pyarrow/0.6.0 when looking for download links for pyarrow==0.6.0
  Ignoring link https://pypi.python.org/packages/21/8f/afae2b4b61ccd38732270fa26df04f7409eb10b64cf5881c56e50c6209af/pyarrow-0.3.0.tar.gz#md5=8f4f44cc0042994aa3e761488625d587 (from https://pypi.python.org/simple/pyarrow/), version 0.3.0 doesn't match ==0.6.0
  Ignoring link https://pypi.python.org/packages/67/7d/06c8b820c6289cdd46307fec33bcf55e59e8d4d54e1776266d0d0d1d2f83/pyarrow-0.2.0.tar.gz#md5=8cbb2769bb6594fe1839510f067d480f (from https://pypi.python.org/simple/pyarrow/), version 0.2.0 doesn't match ==0.6.0
  Could not find a version that satisfies the requirement pyarrow==0.6.0 (from versions: 0.3.0, 0.2.0)
Cleaning up...
No distributions matching the version for pyarrow==0.6.0
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1178, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 322, in find_requirement
    raise DistributionNotFound('No distributions matching the version for %s' % req)
DistributionNotFound: No distributions matching the version for pyarrow==0.6.0

Storing debug log for failure in /root/.pip/pip.log
```

I downloaded the wheel locally, but it cannot be installed:

```java
# pip install --verbose pyarrow-0.6.0-cp27-cp27mu-manylinux1_x86_64.whl  
pyarrow-0.6.0-cp27-cp27mu-manylinux1_x86_64.whl is not a supported wheel on this platform.
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 269, in run
    InstallRequirement.from_line(name, None))
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 168, in from_line
    raise UnsupportedWheel("%s is not a supported wheel on this platform." % wheel.filename)
UnsupportedWheel: pyarrow-0.6.0-cp27-cp27mu-manylinux1_x86_64.whl is not a supported wheel on this platform.

Storing debug log for failure in /root/.pip/pip.log
```

System info:

```java
# uname -a
Linux b31005df8d85 4.11.12-100.fc24.x86_64 #1 SMP Fri Jul 21 17:35:20 UTC 2017 x86_64 GNU/Linux
# python
Python 2.7.9 (default, Jun 29 2016, 13:08:31) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pip
>>> print(pip.pep425tags.get_supported())
[('cp27', 'cp27mu', 'manylinux1_x86_64'), ('cp27', 'cp27mu', 'linux_x86_64'), ('cp27', 'none', 'manylinux1_x86_64'), ('cp27', 'none', 'linux_x86_64'), ('py2', 'none', 'manylinux1_x86_64'), ('py2', 'none', 'linux_x86_64'), ('cp27', 'none', 'any'), ('cp2', 'none', 'any'), ('py27', 'none', 'any'), ('py2', 'none', 'any'), ('py26', 'none', 'any'), ('py25', 'none', 'any'), ('py24', 'none', 'any'), ('py23', 'none', 'any'), ('py22', 'none', 'any'), ('py21', 'none', 'any'), ('py20', 'none', 'any')]
>>> pip.__version__
'9.0.1'
```

**Comment by toddfarmer** [comment]
***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-1378?focusedCommentId=16134293) by Wes McKinney (wesm):*
That's very odd. How did you install pip? As one way to unblock yourself, you can use miniconda and install pyarrow from conda-forge

**Comment by toddfarmer** [comment]
***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-1378?focusedCommentId=16134298) by Rares Vernica (rvernica):*
To install pip, I did:
```java
# apt install python-pip
# pip install --upgrade pip
```

**Comment by toddfarmer** [comment]
***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-1378?focusedCommentId=16134610) by Wes McKinney (wesm):*
pip has warnings about installing / upgrading pip outside of the Linux package manager: https://pip.pypa.io/en/stable/installing/. I am not sure if that is the problem. We may have to seek help upstream from the pypa folks

**Comment by toddfarmer** [comment]
***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-1378?focusedCommentId=16134615) by Rares Vernica (rvernica):*
I think you are right. I tried again from scratch and installed pip with:
```java
# python get-pip.py
```
This time installing pyarrow worked fine.
