### ISSUE TITLE
[Python] Error loading parquet file with _metadata from HDFS

### ISSUE THREAD

**Issue by toddfarmer** [toddfarmer/arrow-migration#1378]
***Note**: This issue was originally created as [ARROW-1429](https://issues.apache.org/jira/browse/ARROW-1429). Please see the [migration documentation](https://gist.github.com/toddfarmer/12aa88361532d21902818a6044fda4c3) for further details.*

### Original Issue Description:
I can open tables stored on HDFS as long as there is no _metadata file besides the parquet files.

For two tables with a _metadata file I get the following traceback:

```Java
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/bmachie/Documents/ml_irissearch/python/util.py", line 199, in read_table
    pq_table = read_hdfs_parquet(hdfs_path, columns)
  File "/home/bmachie/Documents/ml_irissearch/python/util.py", line 251, in read_hdfs_parquet
    return HDFS_CONNECTION.read_parquet(hdfs_path, columns)
  File "/data/data01/dev/edl/infra/mstr/landing/condaenvs/ml_irissearch/lib/python3.5/site-packages/pyarrow/filesystem.py", line 168, in read_parquet
    filesystem=self)
  File "/data/data01/dev/edl/infra/mstr/landing/condaenvs/ml_irissearch/lib/python3.5/site-packages/pyarrow/parquet.py", line 535, in __init__
    self.common_metadata = ParquetFile(self.metadata_path).metadata
  File "/data/data01/dev/edl/infra/mstr/landing/condaenvs/ml_irissearch/lib/python3.5/site-packages/pyarrow/parquet.py", line 54, in __init__
    self.reader.open(source, metadata=metadata)
  File "_parquet.pyx", line 398, in pyarrow._parquet.ParquetReader.open
  File "io.pxi", line 705, in pyarrow.lib.get_reader
  File "io.pxi", line 472, in pyarrow.lib.memory_map
  File "io.pxi", line 451, in pyarrow.lib.MemoryMappedFile._open
  File "error.pxi", line 72, in pyarrow.lib.check_status
pyarrow.lib.ArrowIOError: Failed to open local file: hdfs://nameservice1/path/to/table/_metadata
```

For another table with a _metadata file:

```Java
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/bmachie/Documents/ml_irissearch/python/util.py", line 199, in read_table
    pq_table = read_hdfs_parquet(hdfs_path, columns)
  File "/home/bmachie/Documents/ml_irissearch/python/util.py", line 251, in read_hdfs_parquet
    return HDFS_CONNECTION.read_parquet(hdfs_path, columns)
  File "/data/data01/dev/edl/infra/mstr/landing/condaenvs/ml_irissearch/lib/python3.5/site-packages/pyarrow/filesystem.py", line 168, in read_parquet
    filesystem=self)
  File "/data/data01/dev/edl/infra/mstr/landing/condaenvs/ml_irissearch/lib/python3.5/site-packages/pyarrow/parquet.py", line 548, in __init__
    self.validate_schemas()
  File "/data/data01/dev/edl/infra/mstr/landing/condaenvs/ml_irissearch/lib/python3.5/site-packages/pyarrow/parquet.py", line 557, in validate_schemas
    self.schema = self.pieces[0].get_metadata(open_file).schema
IndexError: list index out of range
```

**Comment by toddfarmer** [comment]
***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-1429?focusedCommentId=16145237) by Brecht Machiels (brechtm):*
For the last table (IndexError), this is because the directory on HDFS is empty (so, no _metadata file either). PyArrow could raise an exception with a more helpful message.

**Comment by toddfarmer** [comment]
***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-1429?focusedCommentId=16145257) by Brecht Machiels (brechtm):*
After renaming `_metadata` to `metadata` on HDFS, the tables can be loaded.

**Comment by toddfarmer** [comment]
***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-1429?focusedCommentId=16145348) by Wes McKinney (wesm):*
Thanks. Seems like there are a couple of improvements that can be made here

**Comment by toddfarmer** [comment]
***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-1429?focusedCommentId=16145358) by Brecht Machiels (brechtm):*
I managed to fix the issue with this simple adjustment: https://github.com/apache/arrow/pull/1009

**Comment by toddfarmer** [comment]
***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-1429?focusedCommentId=16146618) by Wes McKinney (wesm):*
Issue resolved by pull request 1013
<https://github.com/apache/arrow/pull/1013>

**Comment by toddfarmer** [comment]
***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-1429?focusedCommentId=16148632) by Brecht Machiels (brechtm):*
Thanks, Wes!

Looking at the list of open issues for 0.7.0, I assume the next release will not be here soon? It's just that I don't want to spend time building a patched package if 0.7.0 will be available next week.

**Comment by toddfarmer** [comment]
***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-1429?focusedCommentId=16148897) by Wes McKinney (wesm):*
Check out the nightly builds on the twosigma channel on anaconda.org

`conda install pyarrow -c twosigma`

https://anaconda.org/twosigma/pyarrow

This should already include this patch

**Comment by toddfarmer** [comment]
***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-1429?focusedCommentId=16148898) by Wes McKinney (wesm):*
0.7.0 will most hopefully be released the week of 9/10 depending on how things go

**Comment by toddfarmer** [comment]
***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-1429?focusedCommentId=16148899) by Brecht Machiels (brechtm):*
Thanks! I didn't know about the nightly builds.

**Comment by toddfarmer** [comment]
***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-1429?focusedCommentId=16148901) by Wes McKinney (wesm):*
They are very new, `[~cpcloud]` just set them up. We need to add to website (though it will be clear that nightly dev builds are _not_ releases)
