### ISSUE TITLE
listing empty HDFS directory returns an error instead of returning empty list

### ISSUE THREAD

**Issue by toddfarmer** [toddfarmer/arrow-migration#564]
***Note**: This issue was originally created as [ARROW-805](https://issues.apache.org/jira/browse/ARROW-805). Please see the [migration documentation](https://gist.github.com/toddfarmer/12aa88361532d21902818a6044fda4c3) for further details.*

### Original Issue Description:
https://github.com/apache/arrow/blob/master/cpp/src/arrow/io/hdfs.cc#L409-L410

```Java
    if (entries == nullptr) {
      // If the directory is empty, entries is NULL but errno is 0. Non-zero
      // errno indicates error
      //
      // Note: errno is thread-locala
      if (errno == 0) { num_entries = 0; }
      { return Status::IOError("HDFS: list directory failed"); }
    }
```

I think that should have an else:

```Java
    if (entries == nullptr) {
      // If the directory is empty, entries is NULL but errno is 0. Non-zero
      // errno indicates error
      //
      // Note: errno is thread-locala
      if (errno == 0) {
        num_entries = 0;
      } else {
        return Status::IOError("HDFS: list directory failed");
      }
    }
```

**Comment by toddfarmer** [comment]
***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-805?focusedCommentId=15964426) by Wes McKinney (wesm):*
Marked for 0.3

**Comment by toddfarmer** [comment]
***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-805?focusedCommentId=15964439) by Leif Mortenson (leif):*
Does that fix look right? If so I can implement and test.

**Comment by toddfarmer** [comment]
***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-805?focusedCommentId=15964444) by Wes McKinney (wesm):*
Looks right, yep

**Comment by toddfarmer** [comment]
***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-805?focusedCommentId=15964452) by Wes McKinney (wesm):*
`[~cpcloud]` has a docker image with HDFS (and Hive/Impala) that we may be able to use for testing HDFS in a portable way. I currently run the tests against a local cluster, but it's pretty ad hoc.

**Comment by toddfarmer** [comment]
***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-805?focusedCommentId=15964455) by Phillip Cloud (cpcloud):*
Here's a link to the image: https://hub.docker.com/r/cpcloud86/impala/

**Comment by toddfarmer** [comment]
***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-805?focusedCommentId=15964458) by Leif Mortenson (leif):*
How should I use that?  docker run bash and build/run tests in there?  Any env vars I need to set?

**Comment by toddfarmer** [comment]
***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-805?focusedCommentId=15964461) by Wes McKinney (wesm):*
Check out https://github.com/cloudera/ibis/blob/master/circle.yml

**Comment by toddfarmer** [comment]
***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-805?focusedCommentId=15964499) by Leif Mortenson (leif):*
Okay, I got it set up but got a failure, I think it might be failing a permission check?  Not sure yet.

```
ARROW_HDFS_TEST_PORT=9000 ARROW_HDFS_TEST_USER=hdfs ARROW_HDFS_TEST_HOST=impala debug/io-hdfs-test
[==========] Running 18 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 9 tests from TestHdfsClient/0, where TypeParam = arrow::io::JNIDriver
[ RUN      ] TestHdfsClient/0.ConnectsAgain
2017-04-11 11:13:25,511 WARN  [main] util.NativeCodeLoader (NativeCodeLoader.java:<clinit>(62)) - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[       OK ] TestHdfsClient/0.ConnectsAgain (1381 ms)
[ RUN      ] TestHdfsClient/0.CreateDirectory
/home/leif/git/arrow/cpp/src/arrow/io/io-hdfs-test.cc:174: Failure
Value of: s.ok()
  Actual: false
Expected: true
[  FAILED  ] TestHdfsClient/0.CreateDirectory, where TypeParam = arrow::io::JNIDriver (201 ms)
[ RUN      ] TestHdfsClient/0.GetCapacityUsed
[       OK ] TestHdfsClient/0.GetCapacityUsed (137 ms)
[ RUN      ] TestHdfsClient/0.GetPathInfo
[       OK ] TestHdfsClient/0.GetPathInfo (799 ms)
[ RUN      ] TestHdfsClient/0.AppendToFile
2017-04-11 11:13:27,536 WARN  [Thread-15] hdfs.DFSClient (DFSOutputStream.java:run(557)) - DataStreamer Exception
java.io.IOException: Failed to replace a bad datanode on the existing pipeline due to no more good datanodes being available to try. (Nodes: current=[DatanodeInfoWithStorage[172.17.0.2:50010,DS-12c742d4-9f2f-46b4-a512-ee1a1ebd732b,DISK]], original=[DatanodeInfoWithStorage[172.17.0.2:50010,DS-12c742d4-9f2f-46b4-a512-ee1a1ebd732b,DISK]]). The current failed datanode replacement policy is DEFAULT, and a client may configure this via 'dfs.client.block.write.replace-datanode-on-failure.policy' in its configuration.
	at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.findNewDatanode(DFSOutputStream.java:914)
	at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.addDatanode2ExistingPipeline(DFSOutputStream.java:988)
	at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.setupPipelineForAppendOrRecovery(DFSOutputStream.java:1156)
	at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.run(DFSOutputStream.java:454)
FSDataOutputStream#close error:
java.io.IOException: Failed to replace a bad datanode on the existing pipeline due to no more good datanodes being available to try. (Nodes: current=[DatanodeInfoWithStorage[172.17.0.2:50010,DS-12c742d4-9f2f-46b4-a512-ee1a1ebd732b,DISK]], original=[DatanodeInfoWithStorage[172.17.0.2:50010,DS-12c742d4-9f2f-46b4-a512-ee1a1ebd732b,DISK]]). The current failed datanode replacement policy is DEFAULT, and a client may configure this via 'dfs.client.block.write.replace-datanode-on-failure.policy' in its configuration.
	at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.findNewDatanode(DFSOutputStream.java:914)
	at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.addDatanode2ExistingPipeline(DFSOutputStream.java:988)
	at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.setupPipelineForAppendOrRecovery(DFSOutputStream.java:1156)
	at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.run(DFSOutputStream.java:454)
/home/leif/git/arrow/cpp/src/arrow/io/io-hdfs-test.cc:236: Failure
Failed
IOError: HDFS: CloseFile failed
2017-04-11 11:13:27,550 ERROR [main] hdfs.DFSClient (DFSClient.java:closeAllFilesBeingWritten(940)) - Failed to close inode 16419
java.io.IOException: Failed to replace a bad datanode on the existing pipeline due to no more good datanodes being available to try. (Nodes: current=[DatanodeInfoWithStorage[172.17.0.2:50010,DS-12c742d4-9f2f-46b4-a512-ee1a1ebd732b,DISK]], original=[DatanodeInfoWithStorage[172.17.0.2:50010,DS-12c742d4-9f2f-46b4-a512-ee1a1ebd732b,DISK]]). The current failed datanode replacement policy is DEFAULT, and a client may configure this via 'dfs.client.block.write.replace-datanode-on-failure.policy' in its configuration.
	at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.findNewDatanode(DFSOutputStream.java:914)
	at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.addDatanode2ExistingPipeline(DFSOutputStream.java:988)
	at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.setupPipelineForAppendOrRecovery(DFSOutputStream.java:1156)
	at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.run(DFSOutputStream.java:454)
[  FAILED  ] TestHdfsClient/0.AppendToFile, where TypeParam = arrow::io::JNIDriver (207 ms)
```

`[~cpcloud]` maybe we can look together this afternoon?

**Comment by toddfarmer** [comment]
***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-805?focusedCommentId=15965024) by Leif Mortenson (leif):*
Good news, everyone!  I got these tests to pass.  I had to run them in a separate docker container that was linked with the hdfs one though, which isn't great.  I'll try my hand at automating it tonight but don't expect to get that far.

This PR has my changes but not CI changes https://github.com/apache/arrow/pull/528

I think we should deal with CI in a separate PR, though I will start working on it now.

**Comment by toddfarmer** [comment]
***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-805?focusedCommentId=15965027) by Leif Mortenson (leif):*
Living proof:

```
ubuntu@49b5b4f128cb:~/build$ ARROW_HDFS_TEST_PORT=9000 ARROW_HDFS_TEST_USER=hdfs ARROW_HDFS_TEST_HOST=impala debug/io-hdfs-test 
[==========] Running 18 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 9 tests from TestHdfsClient/0, where TypeParam = arrow::io::JNIDriver
[ RUN      ] TestHdfsClient/0.ConnectsAgain
17/04/11 22:06:02 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
17/04/11 22:06:03 WARN shortcircuit.DomainSocketFactory: The short-circuit local reads feature cannot be used because libhadoop cannot be loaded.
[       OK ] TestHdfsClient/0.ConnectsAgain (1837 ms)
[ RUN      ] TestHdfsClient/0.CreateDirectory
[       OK ] TestHdfsClient/0.CreateDirectory (211 ms)
[ RUN      ] TestHdfsClient/0.GetCapacityUsed
[       OK ] TestHdfsClient/0.GetCapacityUsed (156 ms)
[ RUN      ] TestHdfsClient/0.GetPathInfo
[       OK ] TestHdfsClient/0.GetPathInfo (393 ms)
[ RUN      ] TestHdfsClient/0.AppendToFile
[       OK ] TestHdfsClient/0.AppendToFile (232 ms)
[ RUN      ] TestHdfsClient/0.ListDirectory
[       OK ] TestHdfsClient/0.ListDirectory (228 ms)
[ RUN      ] TestHdfsClient/0.ReadableMethods
[       OK ] TestHdfsClient/0.ReadableMethods (230 ms)
[ RUN      ] TestHdfsClient/0.LargeFile
[       OK ] TestHdfsClient/0.LargeFile (263 ms)
[ RUN      ] TestHdfsClient/0.RenameFile
[       OK ] TestHdfsClient/0.RenameFile (192 ms)
[----------] 9 tests from TestHdfsClient/0 (3742 ms total)

[----------] 9 tests from TestHdfsClient/1, where TypeParam = arrow::io::PivotalDriver
[ RUN      ] TestHdfsClient/1.ConnectsAgain
[       OK ] TestHdfsClient/1.ConnectsAgain (150 ms)
[ RUN      ] TestHdfsClient/1.CreateDirectory
[       OK ] TestHdfsClient/1.CreateDirectory (156 ms)
[ RUN      ] TestHdfsClient/1.GetCapacityUsed
[       OK ] TestHdfsClient/1.GetCapacityUsed (127 ms)
[ RUN      ] TestHdfsClient/1.GetPathInfo
[       OK ] TestHdfsClient/1.GetPathInfo (196 ms)
[ RUN      ] TestHdfsClient/1.AppendToFile
[       OK ] TestHdfsClient/1.AppendToFile (225 ms)
[ RUN      ] TestHdfsClient/1.ListDirectory
[       OK ] TestHdfsClient/1.ListDirectory (230 ms)
[ RUN      ] TestHdfsClient/1.ReadableMethods
[       OK ] TestHdfsClient/1.ReadableMethods (195 ms)
[ RUN      ] TestHdfsClient/1.LargeFile
[       OK ] TestHdfsClient/1.LargeFile (251 ms)
[ RUN      ] TestHdfsClient/1.RenameFile
[       OK ] TestHdfsClient/1.RenameFile (189 ms)
[----------] 9 tests from TestHdfsClient/1 (1719 ms total)

[----------] Global test environment tear-down
[==========] 18 tests from 2 test cases ran. (5462 ms total)
[  PASSED  ] 18 tests.
```

**Comment by toddfarmer** [comment]
***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-805?focusedCommentId=15965039) by Wes McKinney (wesm):*
I don't think we'll be able to run this CI in the main repo unless we can get Circle CI. We should set up an arrow-hadoop repository someplace (I can volunteer wesm/arrow-hadoop) where we have more admin control

**Comment by toddfarmer** [comment]
***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-805?focusedCommentId=15965046) by Leif Mortenson (leif):*
Ok then, let's just focus on merging this then.

**Comment by toddfarmer** [comment]
***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-805?focusedCommentId=15965047) by Leif Mortenson (leif):*
Ok then, let's just focus on merging this then.

**Comment by toddfarmer** [comment]
***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-805?focusedCommentId=15965094) by Wes McKinney (wesm):*
Issue resolved by pull request 528
<https://github.com/apache/arrow/pull/528>

**Comment by toddfarmer** [comment]
***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-805?focusedCommentId=16555490) by Manu Zhang (mauzhang):*
If we are sure the error is empty directory why not just return "empty directory" ? It's unclear what the root cause is from "list directory failed".

**Comment by toddfarmer** [comment]
***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-805?focusedCommentId=16555667) by Wes McKinney (wesm):*
We just worked on this again in https://github.com/apache/arrow/commit/eaa60538ae776a0e4c984e6c661ba3f64def98ab. Have a look

**Comment by toddfarmer** [comment]
***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-805?focusedCommentId=16556792) by Manu Zhang (mauzhang):*
Great but I don't see any changes to the error message.

**Comment by toddfarmer** [comment]
***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-805?focusedCommentId=16558242) by Wes McKinney (wesm):*
On master branch? Can you please open a new JIRA?

**Comment by toddfarmer** [comment]
***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-805?focusedCommentId=16558305) by Manu Zhang (mauzhang):*
Opened https://issues.apache.org/jira/browse/ARROW-2919. Thanks
