### ISSUE TITLE
on import get libjemalloc.so.2: cannot allocate memory in static TLS block

### ISSUE THREAD

**Issue by toddfarmer** [toddfarmer/arrow-migration#713]
***Note**: This issue was originally created as [ARROW-1141](https://issues.apache.org/jira/browse/ARROW-1141). Please see the [migration documentation](https://gist.github.com/toddfarmer/12aa88361532d21902818a6044fda4c3) for further details.*

### Original Issue Description:
KevinGre@KevinGreLapX:~/Python$ bin/python
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:53:06)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyarrow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/KevinGre/Python/lib/python3.5/site-packages/pyarrow/__init__.py", line 28, in <module>
    from pyarrow.lib import cpu_count, set_cpu_count
ImportError: /home/KevinGre/Python/lib/python3.5/site-packages/pyarrow/../../.././libjemalloc.so.2: cannot allocate memory in static TLS block

**Comment by toddfarmer** [comment]
***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-1141?focusedCommentId=16060138) by Kevin Grealish (KevinGre):*
Let me know what info you need to repro. This occurs running in a Ubuntu 16.04 based data science VM in Azure. Also repros using the Linux sub-system on windows (Bash on windows). Some details from a coda info:
/Python/bin/conda info
Current conda install:

               platform : linux-64
          conda version : 4.2.12
       conda is private : False
      conda-env version : 4.2.12
    conda-build version : not installed
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : /home/kevingre/Python  (writable)
    default environment : /home/kevingre/Python
       envs directories : /home/kevingre/Python/envs
          package cache : /home/kevingre/Python/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
            config file : /home/kevingre/Python/.condarc
           offline mode : False

**Comment by toddfarmer** [comment]
***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-1141?focusedCommentId=16060143) by Wes McKinney (wesm):*
Can you let us know if downgrading to jemalloc=4.4.0 makes the problem go away?

**Comment by toddfarmer** [comment]
***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-1141?focusedCommentId=16060148) by Kevin Grealish (KevinGre):*
downgrading jemalloc does permit the import to complete:
jemalloc: 5.0.0-0 conda-forge --> 4.4.0-0 conda-forge

**Comment by toddfarmer** [comment]
***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-1141?focusedCommentId=16060150) by Wes McKinney (wesm):*
OK, in the meantime I've suggested disabling static TLS in the jemalloc 5.0.0 in conda-forge https://github.com/conda-forge/jemalloc-feedstock/issues/3

**Comment by toddfarmer** [comment]
***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-1141?focusedCommentId=16060165) by Kevin Grealish (KevinGre):*
Should I expect to need to downgrade on all platforms (windows. mac)? Any guidance on when I will need to set the specific version of jemalloc to avoid this issue?

**Comment by toddfarmer** [comment]
***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-1141?focusedCommentId=16060198) by Wes McKinney (wesm):*
Depending on the outcome of the discussion on the issue I linked we will either fix the 5.0.0 package or update pyarrow to be pinned on 4.4.0

**Comment by toddfarmer** [comment]
***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-1141?focusedCommentId=16061622) by Wes McKinney (wesm):*
This should be resolved now, can you confirm all is OK with jemalloc 5.0.0?

**Comment by toddfarmer** [comment]
***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-1141?focusedCommentId=16063700) by Kevin Grealish (KevinGre):*
Wes, looks like I need to enlist and build to test 0.5.0. Is there an easier options (other drop point perhaps)? If not, I'll look at the build option.

**Comment by toddfarmer** [comment]
***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-1141?focusedCommentId=16063736) by Wes McKinney (wesm):*
I updated the jemalloc conda-forge package which should have fixed the problem, so you can verify with the 0.4.1 pyarrow from conda-forge

**Comment by toddfarmer** [comment]
***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-1141?focusedCommentId=16063759) by Kevin Grealish (KevinGre):*
After bin/conda install pyarrow jemalloc
which did:
jemalloc: 4.4.0-0 conda-forge --> 5.0.0-1 conda-forge
parquet-cpp: 1.1.0-2           conda-forge --> 1.2.0.pre-0       conda-forge
pyarrow:     0.4.0-np111py35_0 conda-forge --> 0.4.1-np111py35_0 conda-forge
I still repro the problem.

**Comment by toddfarmer** [comment]
***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-1141?focusedCommentId=16063770) by Kevin Grealish (KevinGre):*
retried with 
bin/conda  uninstall -c conda-forge  pyarrow jemalloc
bin/conda  install -c conda-forge  pyarrow jemalloc

The following NEW packages will be INSTALLED:

    arrow-cpp:   0.4.1-np111py35_2 conda-forge
    jemalloc:    5.0.0-1           conda-forge
    parquet-cpp: 1.2.0.pre-0       conda-forge
    pyarrow:     0.4.1-np111py35_0 conda-forge

still failed to import pyarrow. Am I missing something?

**Comment by toddfarmer** [comment]
***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-1141?focusedCommentId=16063781) by Wes McKinney (wesm):*
Nope. I'm able to repro the problem now after some twiddling, so I will try to sort out a resolution

**Comment by toddfarmer** [comment]
***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-1141?focusedCommentId=16063790) by Wes McKinney (wesm):*
`[~xhochy]` I'm going to pin arrow-cpp in conda-forge on jemalloc 4.4.0 until we understand how to fix this with 5.0.0

**Comment by toddfarmer** [comment]
***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-1141?focusedCommentId=16065742) by Wes McKinney (wesm):*
We've removed the jemalloc 5.0.0 conda-forge packages so we should be good to go now

**Comment by toddfarmer** [comment]
***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-1141?focusedCommentId=16065781) by Kevin Grealish (KevinGre):*
Verified that installing pyarrow (0.4.0 or 0.4.1) does now only pull jemalloc 4.4.0-0.
