### ISSUE TITLE
libjemalloc.so.2: cannot open shared object file: 

### ISSUE THREAD

**Issue by toddfarmer** [toddfarmer/arrow-migration#933]
***Note**: This issue was originally created as [ARROW-909](https://issues.apache.org/jira/browse/ARROW-909). Please see the [migration documentation](https://gist.github.com/toddfarmer/12aa88361532d21902818a6044fda4c3) for further details.*

### Original Issue Description:
>>> import pyarrow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/default/src/venv/lib/python2.7/site-packages/pyarrow-0.2.1.dev244+g14bec24-py2.7-linux-x86_64.egg/pyarrow/__init__.py", line 28, in <module>
    import pyarrow._config
ImportError: libjemalloc.so.2: cannot open shared object file: No such file or directory

$LD_LIBRARY_PATH has libarrow_jemalloc.a along with other libraries including libarrow.so,  libparquet.so, libparquet_arrow.so. Pyarrow was built using ----with-jemalloc and parquet-cpp was cmake-d with 
-DPARQUET_ARROW=ON  

Also, noticed that arrow/python documentation has been cleaned up with the installation instructions having the coda approach only .Is this the only supported way going forward ?

**Comment by toddfarmer** [comment]
***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-909?focusedCommentId=15989459) by Wes McKinney (wesm):*
hi `[~abdulrahman004]`. Do you have the jemalloc libraries installed in your system? `libjemalloc` must be in your library loader path; having `libarrow_jemalloc.so` is not enough because this is only a binding to Arrow's memory allocator. So either install jemalloc on your system or simply don't build that extension. We have provided for building jemalloc in the C++ libraries' thirdparty stack to facilitate cross-platform packaging (e.g. manylinux1 for Python packages). The expectation is that it will be separately installed on the system where it's deployed. 

> Also, noticed that arrow/python documentation has been cleaned up with the installation instructions having the coda approach only .Is this the only supported way going forward ?

I guess we have to define "supported". It's hard for us to be on the hook to debug build issues on any arbitrary platform. I added the conda build because that's reasonably portable, and doesn't involve platform specific details (like Linux package managers, or Homebrew). It would be great if you or other could contribute reproducible build instructions for other platforms and package managers. I opened https://issues.apache.org/jira/browse/ARROW-911 to cover this. It would be good to have a build guide for macOS, Ubuntu 14.04 and 16.04, and CentOS/RedHat 6 and/or 7. Since most of the dependencies build out of the box, there will be minimal pre-requisites to install from apt-get/yum/Homebrew. Patches welcome.

**Comment by toddfarmer** [comment]
***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-909?focusedCommentId=15989528) by Wes McKinney (wesm):*
I opened ARROW-913 to make the user experience with jemalloc a bit more pleasant (only complain when you try to use the extension)

**Comment by toddfarmer** [comment]
***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-909?focusedCommentId=15989684) by Abdul Rahman (abdulrahman004):*
`[~wesmckinn]` Thanks. I noticed arrow/cpp does have jemalloc in the build folder, but doesnt load them in system libraries.

**Comment by toddfarmer** [comment]
***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-909?focusedCommentId=15999551) by Uwe Korn (uwe):*
`[~abdulrahman004]` Did you have any special compilation/linking options set? Normally `pyarrow/_config.so` should not link to `libjemalloc.so.2`. If you are able to run `lddtree pyarrow/_config.so`, it would really help me to understand where the linkage is coming from.

I made PR https://github.com/apache/arrow/pull/651 to cover for the initial problem that when building jemalloc as an external project it should be statically linked as the shared library is not installed on `make install`.

**Comment by toddfarmer** [comment]
***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-909?focusedCommentId=15999603) by Wes McKinney (wesm):*
Issue resolved by pull request 651
<https://github.com/apache/arrow/pull/651>
